"""add cpu and memory usage to devices

Revision ID: 1d3ab9e4130a
Revises: ea7fe2e0f0fa
Create Date: 2026-03-04 11:00:22.006284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d3ab9e4130a'
down_revision: Union[str, Sequence[str], None] = 'ea7fe2e0f0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('memory_usage', sa.Float(), nullable=True))
    op.alter_column('devices', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('devices', 'memory_usage')
    op.drop_column('devices', 'cpu_usage')
    # ### end Alembic commands ###
